name: Update Internet Archive Data
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
jobs:
  update-data:
    name: Update Internet Archive Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python update_archive.py
      - name: Commit Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Internet Archive Data
